export const APIKEY = 'cfe422613b250f702980a3bbf9e90716';

export const GET_CONFIG = 'GET_CONFIG';
export const GET_MOVIE_TMDB = 'GET_MOVIE_TMDB';
export const GET_MOVIES_TMDB = 'GET_MOVIES_TMDB';
export const GET_GENRES_TMDB = 'GET_GENRES_TMDB';

export const GET_PERSON_TMDB = 'GET_PERSON_TMDB';
export const GET_TOPMOVIES_TMDB = 'GET_TOPMOVIES_TMDB';
export const GET_NPMOVIES_TMDB = 'GET_NPMOVIES_TMDB';
export const GET_UCMOVIES_TMDB = 'GET_UCMOVIES_TMDB';
export const GET_TOPPEOPLE_TMDB = 'GET_TOPPEOPLE_TMDB';

export const ADD_WATCHLIST_MOVIE_TMDB = 'ADD_WATCHLIST_MOVIE_TMDB';
export const ADD_USER_MOVIE = 'ADD_USER_MOVIE';
export const REMOVE_USER_MOVIE = 'REMOVE_USER_MOVIE';
export const REMOVE_WATCHLIST_MOVIE = 'REMOVE_WATCHLIST_MOVIE';

export const AUTH_USER_SET = 'AUTH_USER_SET';
export const USER_SET = 'USER_SET';
